const StatusCodes = {
  ACCEPTED: 202,
  BAD_GATEWAY: 502,
  BAD_REQUEST: 400,
  CONFLICT: 409,
  CONTINUE: 100,
  CREATED: 201,
  EXPECTATION_FAILED: 417,
  FAILED_DEPENDENCY: 424,
  FORBIDDEN: 403,
  GATEWAY_TIMEOUT: 504,
  GONE: 410,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  IM_A_TEAPOT: 418,
  INSUFFICIENT_SPACE_ON_RESOURCE: 419,
  INSUFFICIENT_STORAGE: 507,
  INTERNAL_SERVER_ERROR: 500,
  LENGTH_REQUIRED: 411,
  LOCKED: 423,
  METHOD_FAILURE: 420,
  METHOD_NOT_ALLOWED: 405,
  MOVED_PERMANENTLY: 301,
  MOVED_TEMPORARILY: 302,
  MULTI_STATUS: 207,
  MULTIPLE_CHOICES: 300,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
  NO_CONTENT: 204,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NOT_ACCEPTABLE: 406,
  NOT_FOUND: 404,
  NOT_IMPLEMENTED: 501,
  NOT_MODIFIED: 304,
  OK: 200,
  PARTIAL_CONTENT: 206,
  PAYMENT_REQUIRED: 402,
  PERMANENT_REDIRECT: 308,
  PRECONDITION_FAILED: 412,
  PRECONDITION_REQUIRED: 428,
  PROCESSING: 102,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  REQUEST_TIMEOUT: 408,
  REQUEST_TOO_LONG: 413,
  REQUEST_URI_TOO_LONG: 414,
  REQUESTED_RANGE_NOT_SATISFIABLE: 416,
  RESET_CONTENT: 205,
  SEE_OTHER: 303,
  SERVICE_UNAVAILABLE: 503,
  SWITCHING_PROTOCOLS: 101,
  TEMPORARY_REDIRECT: 307,
  TOO_MANY_REQUESTS: 429,
  UNAUTHORIZED: 401,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  UNPROCESSABLE_ENTITY: 422,
  UNSUPPORTED_MEDIA_TYPE: 415,
  USE_PROXY: 305,
  MISDIRECTED_REQUEST: 421,
};

const StatusMessages = {
  ACCEPTED: "Accepted",
  BAD_GATEWAY: "Bad Gateway",
  BAD_REQUEST: "Bad Request",
  CONFLICT: "Conflict",
  CONTINUE: "Continue",
  CREATED: "Created",
  EXPECTATION_FAILED: "Expectation Failed",
  FAILED_DEPENDENCY: "Failed Dependency",
  FORBIDDEN: "Forbidden",
  GATEWAY_TIMEOUT: "Gateway Timeout",
  GONE: "Gone",
  HTTP_VERSION_NOT_SUPPORTED: "HTTP Version Not Supported",
  IM_A_TEAPOT: "I'm a teapot",
  INSUFFICIENT_SPACE_ON_RESOURCE: "Insufficient Space on Resource",
  INSUFFICIENT_STORAGE: "Insufficient Storage",
  INTERNAL_SERVER_ERROR: "Internal.Server.Error",
  LENGTH_REQUIRED: "Length Required",
  LOCKED: "Locked",
  METHOD_FAILURE: "Method Failure",
  METHOD_NOT_ALLOWED: "Method Not Allowed",
  MOVED_PERMANENTLY: "Moved Permanently",
  MOVED_TEMPORARILY: "Moved Temporarily",
  MULTI_STATUS: "Multi-Status",
  MULTIPLE_CHOICES: "Multiple Choices",
  NETWORK_AUTHENTICATION_REQUIRED: "Network Authentication Required",
  NO_CONTENT: "No Content",
  NON_AUTHORITATIVE_INFORMATION: "Non Authoritative Information",
  NOT_ACCEPTABLE: "Not Acceptable",
  NOT_FOUND: "Not.Found",
  NOT_IMPLEMENTED: "Not Implemented",
  NOT_MODIFIED: "Not Modified",
  OK: "OK",
  PARTIAL_CONTENT: "Partial Content",
  PAYMENT_REQUIRED: "Payment Required",
  PERMANENT_REDIRECT: "Permanent Redirect",
  PRECONDITION_FAILED: "Precondition Failed",
  PRECONDITION_REQUIRED: "Precondition Required",
  PROCESSING: "Processing",
  PROXY_AUTHENTICATION_REQUIRED: "Proxy Authentication Required",
  REQUEST_HEADER_FIELDS_TOO_LARGE: "Request Header Fields Too Large",
  REQUEST_TIMEOUT: "Request Timeout",
  REQUEST_TOO_LONG: "Request Entity Too Large",
  REQUEST_URI_TOO_LONG: "Request-URI Too Long",
  REQUESTED_RANGE_NOT_SATISFIABLE: "Requested Range Not Satisfiable",
  RESET_CONTENT: "Reset Content",
  SEE_OTHER: "See Other",
  SERVICE_UNAVAILABLE: "Service Unavailable",
  SWITCHING_PROTOCOLS: "Switching Protocols",
  TEMPORARY_REDIRECT: "Temporary Redirect",
  TOO_MANY_REQUESTS: "Too Many Requests",
  UNAUTHORIZED: "Unauthorized",
  UNAVAILABLE_FOR_LEGAL_REASONS: "Unavailable For Legal Reasons",
  UNPROCESSABLE_ENTITY: "Unprocessable Entity",
  UNSUPPORTED_MEDIA_TYPE: "Unsupported Media Type",
  USE_PROXY: "Use Proxy",
  MISDIRECTED_REQUEST: "Misdirected Request",
  EMAIL_UNREGISTER: "please register your account this",
};
const responseMessages = {
  USER_LOGIN: "user.login.successfully",
  LOGIN_WRONG_CREDENTIALS: "login.wrong.credentials",
  LOGIN_USER_ALREADY_EXIST: "please.register.your.account.on.email",
  REGISTRATION_USER_ALREADY_EXIST: "registration.already.exist.email",
  USER_REGISTER_CREATED: "register.created.successfully",
  USER_REGISTER_ROLE_NOT_EXIST: "user.register.role.not.exist",
  USER_DELETE_SUCCESSFULL: "user.deleted.successfully",
  USER_UPDATE_SUCCESSFULL: "user.update.successfully",
  USER_GET_ID: "fetched.single.user",
  USER_GET_ALL: "all.user.show",
  USER_PERMISSION_ALLOW: "user.permission.allow",
  USER_INVALID: "invalid.user.id",
  USER_CHECK_EMAIL: "please.check.your.email.then.set.your.password",
  USER_SET_PASSWORD_SUCESSFULL: "user.set.the.password.sucessfully",
  USER_ALREADY_USES: "you.have.already.uses",
  USER_RESET_SUCESSFULL: "password.reset.sucessfully",
  USER_ALREADY_RESET_PASS: "you.have.already.reset.your.password",
  USER_INVALID_LINK: "Invalid.link.or.expired.",
  USER_LOGOUT: "logout.Successfully",
  USER_LOGOUT_ALREADY: "logout.user",
  PRODUCT_ADDED: "product.added",
  PRODUCT_DELETED: "product.deleted",
  PRODUCT_UPDATED: "product.updated",
  PRODUCT_FETCHED: "all.product.fetched",
  PRODUCT_SINGLE_FETCHED: "fetched.single.product",
  PRODUCT_CATEGORY_FETCHED: "all.category.fetched",
  PRODUCT_SEARCHED: "searched.appeared",
  UPLOAD_IMAGE: "files.uploaded",
  UPLOAD_IMAGE_DELETED: "files.deleted",
  UPLOAD_IMAGE_UPDATED: "file.updated",
  MULTIPLE_UPLOAD_IMAGE: "multiple.images.uploaded",
  BAD_REQUEST: "bad.request",
  NOT_VALID_OBJECTID: "NOT.VALID.OBJECTID",
  ERROR_OCCURED_FILES: "error.occured.file",
  VALID_OBJECT_ID: "valid.objectid",
  PRODUCT_OBJECT_ID: "valid.productid",
  INVALID_RESPONSES: "invalid.responses",
  AUCTION_NOT_ADDED: "auction.not.added",
  AUCTION_ADDED: "auction.added",
  AUCTION_UPDATED: "auction.updated",
  AUCTION_DELETED: "auction.deleted",
  SINGLE_AUCTION: "single.auction",
  SEARCHED_AUCTION: "searched.auction",
  AUCTION_DATE: "auction.date",
  AUCTION_QUANTITY: "auction.quantity",
  AUCTION_CANT_DELETE: "auction.cantDelete",
  PRODUCT_OBJECTID: "product.objectid",
  PRODUCT_EXISTS: "product.exists",
  TOKEN_EXPIRED: "Protected resource, token expired",
  BOT_MAX_PRICE: "bot.price",
  SELLING_PRICE: "selling.price",
  AUCTION_TYPE: "auction.type",
};
const privilage = [
  {
    name: "READ",
    description: "only for read permission",
    accessNumber: 1,
  },
  {
    name: "ADD",
    description: "only for created permission",
    accessNumber: 2,
  },
  {
    name: "UPDATE",
    description: "only for update permission",
    accessNumber: 4,
  },
  {
    name: "DELETE",
    description: "only for delete permission",
    accessNumber: 8,
  },
];

const privilageRole = [
  {
    module: [
      {
        name: "products",
        privilageNumber: 15,
      },
      {
        name: "acutions",
        privilageNumber: 15,
      },
      {
        name: "roles",
        privilageNumber: 15,
      },
      {
        name: "users",
        privilageNumber: 15,
      },
    ],
  },
];

const privilageRoleVan = [
  {
    module: [
      {
        name: "products",
        privilageNumber: 7,
      },
      {
        name: "acutions",
        privilageNumber: 7,
      },
      {
        name: "roles",
        privilageNumber: 7,
      },
      {
        name: "users",
        privilageNumber: 7,
      },
    ],
  },
];

const roles = [{ name: "Admin" }, { name: "Vendor" }];

/**
 * @description Product Category Master with all fields
 *
 */
const productCategory = [
  {
    name: "Appliances",
    type: "Physical",
    description:
      "three categories of mobile phones: basic phones, feature phones, and smartphones.",
  },
  {
    name: "Cell Phones & Accessories",
    type: "Digital",
    description:
      "car body types: Hatchback, Sedan, SUV, MUV, Coupe, Convertible, and Pickup Truck.",
  },
  {
    name: "Handmade",
    type: "Physical",
    description:
      "car body types: Hatchback, Sedan, SUV, MUV, Coupe, Convertible, and Pickup Truck.",
  },
  {
    name: "Musical Instrument",
    type: "Physical",
    description:
      "car body types: Hatchback, Sedan, SUV, MUV, Coupe, Convertible, and Pickup Truck.",
  },
  {
    name: "Jewelry",
    type: "Physical",
    description:
      "car body types: Hatchback, Sedan, SUV, MUV, Coupe, Convertible, and Pickup Truck.",
  },
];

export const helpers = {
  responseMessages,
  StatusMessages,
  StatusCodes,
  privilage,
  roles,
  privilageRole,
  privilageRoleVan,
  productCategory,
};
